export const ceny = {
  "Skrzynia Manualna": [
    {
      name: "Kurs Podstawowy",
      price: "3300zł",
      features: [
        "Badania lekarskie - na miejscu",
        "Materiały dydaktyczne",
        "26 godzin - wykłady (1x45 min.)",
        "4 godziny - pierwsza pomoc poszkodowanym (1x45 min)",
        "30 godzin - jazdy (1x60 min)",
        "Możliwość odbycia min. 2 godzin jazdy z automatyczną skrzynią biegów – dla chętnych",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
      ],
      express: [""],
    },
    {
      name: "Kurs Rozszerzony",
      price: "3600zł",
      features: [
        "Badania lekarskie - na miejscu",
        "Materiały dydaktyczne",
        "26 godzin - wykłady (1x 45min.)",
        "4 godziny - pierwsza pomoc poszkodowanym (1x45 min)",
        "30 godzin - jazdy (1x60 min.)",
        "Możliwość odbycia min. 2 godzin jazdy z automatyczną skrzynią biegów – dla chętnych",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
        "4 dodatkowe godziny jazdy (1x60min.), przed egzaminem państwowym",
      ],
      express: [""],
    },
    {
      name: "Kurs Express - jazdy w 16 dni!",
      price: "4000zł",
      features: [
        "Badania lekarskie - na miejscu",
        "Materiały dydaktyczne",
        "26 godzin - wykłady (1x 45min.)",
        "4 godziny - pierwsza pomoc poszkodowanym (1x45 min)",
        "30 godzin - jazdy (1x60 min.)",
        "Możliwość odbycia min. 2 godzin jazdy z automatyczną skrzynią biegów – dla chętnych",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
        "2 dodatkowe godziny jazdy (1x60min.), przed egzaminem państwowym",
        ,
      ],
      express: [
        "Ilość miejsc ograniczona",
        "Potwierdź telefonicznie dostępność!",
      ],
    },
  ],
  "Posiadacze kat. B1": [
    {
      name: "Kurs podstawowy – skrzynia automat",
      price: "2400zł",
      auto: "HYUNDAI i20",
      autoOpis: "Egzamin państwowy na naszym pojeździe!",
      features: [
        "Badania lekarskie - jeśli będzie konieczność wykonania",
        "20 godzin - jazdy (1x60 min.)",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
        "Pierwsze podstawienie pojazdu na egzamin państwowy do WORD",
        "Każde kolejne podstawienie pojazdu do WORD to koszt 200 zł",
      ],
    },
    {
      name: "Kurs podstawowy - skrzynia manualna",
      price: "2200zł",
      auto: "KIA RIO",
      autoOpis: "Egzamin państwowy na pojeździe WORD!",
      features: [
        "Badania lekarskie - jeśli będzie konieczność wykonania",
        "20 godzin - jazdy (1x60 min.)",
        "Możliwość odbycia min. 2 godzin jazdy z automatyczną skrzynią biegów – dla chętnych",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
      ],
    },
  ],
  "Skrzynia Automatyczna": [
    {
      name: "Kurs Podstawowy",
      price: "3600zł",
      features: [
        "Badania lekarskie - na miejscu",
        "Materiały dydaktyczne",
        "26 godzin - wykłady (1x45 min.)",
        "4 godziny - pierwsza pomoc poszkodowanym (1x45 min)",
        "30 godzin - jazdy (1x60 min)",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
        "Pierwsze podstawienie pojazdu na egzamin państwowy do WORD",
        "Drugie podstawienie pojazdu do WORD w przypadku poprawki",
        "Każde kolejne podstawienie pojazdu do WORD to koszt 200 zł",
      ],
      express: [""],
    },
    {
      name: "Kurs Express - jazdy w 16 dni!",
      price: "4000zł",
      features: [
        "Badania lekarskie - na miejscu",
        "Materiały dydaktyczne",
        "26 godzin - wykłady (1x 45min.)",
        "4 godziny - pierwsza pomoc poszkodowanym (1x45 min)",
        "30 godzin - jazdy (1x60 min.)",
        "Egzamin wewnętrzny po zakończeniu szkolenia (teoria + praktyka)",
        "Pierwsze podstawienie pojazdu na egzamin państwowy do WORD",
        "Drugie podstawienie pojazdu do WORD w przypadku poprawki",
        "Każde kolejne podstawienie pojazdu do WORD to koszt 200 zł",
      ],
      express: [
        "Ilość miejsc ograniczona",
        "Potwierdź telefonicznie dostępność!",
      ],
    },
  ],
  "Szkolenia uzupełniające": [
    {
      name: "1 dodatkowa godzina teorii",
      price: "50zł",
      czas: "/ 45min",
      features: [],
    },
    {
      name: "1 dodatkowa godzina praktyki",
      price: "110zł",
      czas: "/ 60min",
      features: [],
    },
    {
      name: "PAKIET - 10 dodatkowych jazd",
      price: "1000zł",
      czas: "/ 10x60min",
      features: ["Obowiązuje przy płatności jednorazowej"],
    },
  ],
};
